# MySQLデータベース
MySQL:
  host: localhost
  port: 3306
  database: krkingdoms
  username: root
  password:

# 派閥の使用不可名
BannedName:
  - none
  - 未所属
  - 所属無し
  - 所有者なし

# 使用ワールド名
WorldName: world

# 領土チャンクの初期HP
# 領土枠解放の値段
Chunk:
  HP: 50
  Price: 10000

# 所持金の上限
# 領土主張の値段
Money:
  Limit: 100000
  Claim: 1000