# MySQLデータベース
MySQL:
  host: localhost
  port: 3306
  database: krkingdoms
  username: root
  password:

# 派閥の使用不可名
BannedName:
  - none
  - 未所属
  - 所属無し
  - 所有者なし

# 使用ワールド名
WorldName: world

# 領土のレベル毎HP
ChunkHP: 50
# 領土のHPLevelの値段
ChunkLevel: 40000
# HPLevelの最大値
ChunkMaxLevel: 100
# HP回復の値段
ChunkRecovery: 1000
# 領土枠解放の値段
ChunkSlot: 10000
# 最大領土枠数
ChunkMaxSlot: 64
# 領土主張の値段
ChunkClaim: 1000
