# MySQLデータベース
MySQL:
  host: localhost
  port: 3306
  database: krkingdoms
  username: root
  password:

# 保護解除までの非ログイン日数
ProtectionDay: 30

# 派閥作成資金
FactionCreate: 80000
# 派閥の使用不可名
FactionBannedName:
  - none
  - 未所属
  - 所属無し
  - 所有者なし
# メンバー枠値段
FactionSlot: 40000
# 最大メンバー数
FactionMember: 16
# 最大味方派閥数
FactionAlly: 10
# 最大敵派閥数
FactionEnemy: 10

# 使用ワールド名
WorldName: world

# 領土のレベル毎HP
ChunkHP: 20
# 領土のHPLevelの値段
ChunkLevel: 40000
# HPLevelの最大値
ChunkMaxLevel: 100
# HP回復の値段
ChunkRecovery: 1000
# 領土枠解放の値段
ChunkSlot: 10000
# 最大領土枠数
ChunkMaxSlot: 64
# 領土主張の値段
ChunkClaim: 1000
