# MySQLデータベース
MySQL:
  host: localhost
  port: 3306
  database: krkingdoms
  username: root
  password:

# 派閥の使用不可名
BannedName:
  - none
  - 未所属
  - 所属無し
  - 所有者なし

# 使用ワールド名
WorldName: world

# 領土のレベル毎HP
Chunk.HP: 50
# 領土のHPLevelの値段
Chunk.Level: 40000
# HPLevelの最大値
Chunk.MaxLevel: 100
# HP回復の値段
Chunk.Recovery: 1000
# 領土枠解放の値段
Chunk.Slot: 10000
# 最大領土枠数
Chunk.MaxSlot: 64
# 領土主張の値段
  Chunk.Claim: 1000
